import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers';
import Navbar from '@/components/navbar';
import Head from 'next/head'; // 引入 Head 组件

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.TITLE ?? "nextArtifacts",
  description: process.env.DESC ?? "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      {process.env.GA_ID && <Head>
        <script async src={`https://www.googletagmanager.com/gtag/js?${process.env.GA_ID}`}></script>
        <script dangerouslySetInnerHTML={{ __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', ${process.env.GA_ID});
        `}} />
      </Head>}
      <body className={inter.className}>
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar githubUrl="https://github.com/etrobot/nextArtifacts" twitterUrl="https://x.com/etrobot" />
          <main className='mx-auto p-2'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
