import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers';
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.TITLE ?? "nextArtifacts",
  description: process.env.DESC ?? "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar githubUrl="https://github.com/etrobot/nextArtifacts" twitterUrl="https://x.com/etrobot" />
          <main className='mx-auto p-2'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}